actors:
  kou:
    image_url: /images/actors/kou.png
    name: kou
    url: https://twitter.com/rgb_kou
  hikaru:
    image_url: /images/actors/hikaru.png
    name: hikaru
    url: https://twitter.com/clone_baal
  HAMINA:
    image_url: /images/actors/hamina.png
    name: HAMINA
    url: https://twitter.com/HAMINA_Nyhem
author: kou, Hikaru
description: 3DCG、ソフトウェア、ハードウェア、ガジェットなどについて話すテック系Podcastです。
description_long: 3DCG、ソフトウェア、ハードウェア、ガジェットなどについて話すテック系Podcast
email: hikarusgcporky.ac@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-129520750-1
hashtag: EA_Net
itunes_podcast_url: https://itunes.apple.com/jp/podcast/empty-attribute/id1445355288?mt=2
keywords: tech,3dcg,technology,programming,podcast,ポッドキャスト,EANET
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Empty Attribute
url: https://emptyattribute.net/